[providers.php]
version = "8.1"
extensions = ["mbstring", "pdo", "pdo_mysql", "curl", "zip", "xml", "bcmath", "intl", "redis"]

[phases.setup]
nixPkgs = ["nodejs-16_x", "npm-8_x"]

[phases.install]
cmds = [
    "npm ci --only=production --no-audit --no-fund",
    "./install.sh"
]

[phases.build]
cmds = [
    "npm run production"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
